import QCryptLean.QKD.BB84.Program
import QCryptLean.LOCC.Typed.ChannelCoordinates
import QCryptLean.LOCC.Typed.Instrument.MatrixConj
import QCryptLean.Quantum.Channels.CPTP.CKRBound.PermutationReduction

/-!
# Reference blocks of the retained BB84 classical tail

This module exposes the exact finite classical kernel of the source-defined
`QKD.BB84.rawClassicalTailProgram`.  Its PE, fused-announcement, final-decision, key, and abort
coordinates are constructed explicitly.  The block theorem is a library calculation for the finite
LOCC program motivated by Renner, arXiv:quant-ph/0512258v2, Section 6.5, and Nahar et al.,
arXiv:2403.11851, Section V.C; it is not a security theorem from those papers. -/

open scoped Matrix BigOperators
open Matrix

noncomputable section

namespace QKD.BB84.Reduction
open TypedLOCC

open TypedLOCC.TwoParty
open QKD.BB84.Engine

/-- The actual PE and fused public data generated by a raw input and a sampled seed pair. -/
def rawClassicalTailDataOf
    (n m ell ellEV : ℕ) (peSel : Fin n → Bool) (leakEC : ℕ)
    (ec : ECScheme n peSel leakEC)
    (x : (FinalStage.rawSystem n).total)
    (st : KeyHashSeedPairEV n ell ellEV peSel) :
    QKD.BB84.ClassicalTailData n m ell ellEV peSel leakEC :=
  let tagSyn := finProdFinEquiv.symm
    (QKD.BB84.Model.evTagSynOf n ell ellEV peSel leakEC ec
      (Fintype.equivFin (KeyHashSeedPairEV n ell ellEV peSel) st) (x .alice))
  { alicePE := fun j =>
      LOCC.registerBit n (bb84PERoundIdx (m := m) peSel j) (x .alice)
    bobPE := fun j =>
      LOCC.registerBit n (bb84PERoundIdx (m := m) peSel j) (x .bob)
    seedPair := st
    evTag := tagSyn.1
    syndrome := tagSyn.2 }

/-- The literal final-stage output generated by semantic public data and one raw input. -/
noncomputable def rawClassicalTailFinalPoint
    (n m ell ellEV : ℕ) (peSel xSel : Fin n → Bool) (leakEC : ℕ)
    (ec : ECScheme n peSel leakEC) (delta Q : ℝ)
    (d : QKD.BB84.ClassicalTailData n m ell ellEV peSel leakEC)
    (x : (FinalStage.rawSystem n).total) :
    (FinalStage.boundary ell).space := by
  let flag := QKD.BB84.Model.acceptFlagOf n m ellEV peSel xSel leakEC ec delta Q
    d.alicePE d.bobPE d.seedPair.2 d.evTag d.syndrome (x .bob)
  by_cases hflag : flag = 0
  · refine (Boundary.publicSpaceEquiv (FinalStage.flagBoundary ell)).symm
      ⟨flag, ?_⟩
    simpa [FinalStage.flagBoundary, hflag] using
      (Boundary.leafSpaceEquiv (FinalStage.keySystem ell)).symm
        ((TwoParty.pairEquiv (Fin (2 ^ ell)) (Fin (2 ^ ell))).symm
          (QKD.BB84.Model.aliceKeySlotOf n ell peSel d.seedPair.1 flag (x .alice),
           QKD.BB84.Model.bobKeySlotOf n ell peSel leakEC ec d.seedPair.1 d.syndrome
             flag (x .bob)))
  · refine (Boundary.publicSpaceEquiv (FinalStage.flagBoundary ell)).symm
      ⟨flag, ?_⟩
    simpa [FinalStage.flagBoundary, hflag] using
      (Boundary.leafSpaceEquiv FinalStage.abortSystem).symm
        ((TwoParty.pairEquiv Unit Unit).symm ((), ()))

/-- The complete grafted output point, retaining every public cell and the ordered local keys. -/
noncomputable def rawClassicalTailOutputPoint
    (n m ell ellEV : ℕ) (peSel xSel : Fin n → Bool) (leakEC : ℕ)
    (ec : ECScheme n peSel leakEC) (delta Q : ℝ)
    (x : (FinalStage.rawSystem n).total)
    (st : KeyHashSeedPairEV n ell ellEV peSel) :
    (QKD.BB84.rawClassicalTailBoundary n m ell ellEV peSel leakEC).space :=
  let d := rawClassicalTailDataOf n m ell ellEV peSel leakEC ec x st
  (Boundary.graftSpaceEquiv
      (QKD.BB84.classicalPreDecisionBoundary n m ell ellEV peSel leakEC)
      (fun _ => FinalStage.boundary ell)).symm
    ⟨(QKD.BB84.classicalTailExitEquiv n m ell ellEV peSel leakEC).symm d,
      rawClassicalTailFinalPoint n m ell ellEV peSel xSel leakEC ec delta Q d x⟩

/-- Entries of the accepting continuation between two key points: Bob's and then Alice's key
functions read the diagonal of the raw registers, and the two key coordinates must both match. -/
private theorem acceptContinuation_denote_apply
    (n ell : ℕ) (peSel : Fin n → Bool) (leakEC : ℕ) (ec : ECScheme n peSel leakEC)
    (seed : KeyHashSeed n ell peSel) (syn : Fin (2 ^ leakEC))
    (flag : Fin 2) (sigma : TypedLOCC.Op (FinalStage.rawSystem n).total)
    (a a' b b' : Fin (2 ^ ell)) :
    (FinalStage.acceptContinuation n ell peSel leakEC ec seed syn flag).denote sigma
        ((Boundary.leafSpaceEquiv (FinalStage.keySystem ell)).symm
          ((TwoParty.pairEquiv _ _).symm (a, b)))
        ((Boundary.leafSpaceEquiv (FinalStage.keySystem ell)).symm
          ((TwoParty.pairEquiv _ _).symm (a', b'))) =
      ∑ y : Fin (2 ^ n),
        if b = QKD.BB84.Model.bobKeySlotOf n ell peSel leakEC ec seed syn flag y ∧
            b' = QKD.BB84.Model.bobKeySlotOf n ell peSel leakEC ec seed syn flag y then
          ∑ x : Fin (2 ^ n),
            if a = QKD.BB84.Model.aliceKeySlotOf n ell peSel seed flag x ∧
                a' = QKD.BB84.Model.aliceKeySlotOf n ell peSel seed flag x then
              sigma ((TwoParty.pairEquiv _ _).symm (x, y))
                ((TwoParty.pairEquiv _ _).symm (x, y))
            else 0
        else 0 := by
  have hout : (FinalStage.bobKeyAction n ell peSel leakEC ec seed syn flag).out =
    FinalStage.keySystem ell := by
    simp only [FinalStage.bobKeyAction, FinalStage.aliceKeyAction,
      PrivateAction.out_ofInstrument, FinalStage.rawSystem, FinalStage.keySystem,
      TwoParty.set_alice, TwoParty.set_bob]
  have hcoord (a b : Fin (2 ^ ell)) :
      (Equiv.cast (congrArg Boundary.space (congrArg Boundary.leaf hout.symm)))
          ((Boundary.leafSpaceEquiv (FinalStage.keySystem ell)).symm
            ((TwoParty.pairEquiv _ _).symm (a, b))) =
        (Boundary.leafSpaceEquiv (FinalStage.bobKeyAction n ell peSel leakEC ec seed syn
          flag).out).symm
          ((FinalStage.bobKeyAction n ell peSel leakEC ec seed syn flag).out.pairEquiv.symm (a,
            b)) := by
    change cast (congrArg (fun T => (Boundary.leaf T).space) hout.symm)
      ((Boundary.leafSpaceEquiv (FinalStage.keySystem ell)).symm
        ((FinalStage.keySystem ell).pairEquiv.symm (a, b))) = _
    rw [Boundary.cast_leafSpaceEquiv_symm hout.symm,
      MultipartiteSystem.cast_pairEquiv_symm hout.symm]
    rfl
  change (FinalStage.acceptContinuation n ell peSel leakEC ec seed syn flag).denote sigma
    ((Boundary.leafSpaceEquiv (FinalStage.keySystem ell)).symm
      ((TwoParty.pairEquiv _ _).symm (a, b)))
    ((Boundary.leafSpaceEquiv (FinalStage.keySystem ell)).symm
      ((TwoParty.pairEquiv _ _).symm (a', b'))) = _
  unfold FinalStage.acceptContinuation
  rw [Program.denote_cast_apply rfl (congrArg Boundary.leaf hout.symm), hcoord, hcoord]
  change ((FinalStage.aliceKeyAction n ell peSel seed flag).then (FinalStage.bobKeyAction n ell
    peSel leakEC ec seed syn flag).run).denote sigma
    ((Boundary.leafSpaceEquiv (FinalStage.bobKeyAction n ell peSel leakEC ec seed syn
      flag).out).symm
      ((FinalStage.bobKeyAction n ell peSel leakEC ec seed syn flag).out.pairEquiv.symm (a, b)))
    ((Boundary.leafSpaceEquiv (FinalStage.bobKeyAction n ell peSel leakEC ec seed syn
      flag).out).symm
      ((FinalStage.bobKeyAction n ell peSel leakEC ec seed syn flag).out.pairEquiv.symm (a', b')))
        = _
  unfold PrivateAction.then PrivateAction.run
  rw [Program.denote_priv_eq_sum_liftedOperation]
  change ((∑ o : Unit, ((FinalStage.bobKeyAction n ell peSel leakEC ec seed syn flag).then
    Program.done).denote ∘ₗ
    (FinalStage.aliceKeyAction n ell peSel seed flag).liftedOperation o) sigma) _ _ = _
  rw [Fintype.sum_unique]
  simp only [LinearMap.comp_apply]
  unfold PrivateAction.then
  rw [Program.denote_priv_eq_sum_liftedOperation]
  change ((∑ o : Unit, Program.done.denote ∘ₗ (FinalStage.bobKeyAction n ell peSel leakEC ec seed
    syn flag).liftedOperation o)
    ((FinalStage.aliceKeyAction n ell peSel seed flag).liftedOperation () sigma)) _ _ = _
  rw [Fintype.sum_unique]
  simp only [LinearMap.comp_apply, Program.denote_done]
  change ((FinalStage.bobKeyAction n ell peSel leakEC ec seed syn flag).liftedOperation ()
    ((FinalStage.aliceKeyAction n ell peSel seed flag).liftedOperation () sigma))
      ((FinalStage.bobKeyAction n ell peSel leakEC ec seed syn flag).out.pairEquiv.symm (a, b))
      ((FinalStage.bobKeyAction n ell peSel leakEC ec seed syn flag).out.pairEquiv.symm (a', b'))
        = _
  change (((Instrument.functionAndForget (QKD.BB84.Model.bobKeySlotOf n ell peSel leakEC ec seed
    syn flag)).liftAt
    (FinalStage.aliceKeyAction n ell peSel seed flag).out .bob).operation ()
      ((FinalStage.aliceKeyAction n ell peSel seed flag).liftedOperation () sigma))
        (((FinalStage.aliceKeyAction n ell peSel seed flag).out.set .bob (Fin (2 ^
          ell))).pairEquiv.symm
          (a, b))
        (((FinalStage.aliceKeyAction n ell peSel seed flag).out.set .bob (Fin (2 ^
          ell))).pairEquiv.symm
          (a', b')) = _
  rw [Instrument.liftAt_bob_operation_apply, Instrument.functionAndForget_operation_apply]
  have hAliceApply (a a' : Fin (2 ^ ell))
      (rB : Fin (2 ^ n)) :
      ((FinalStage.aliceKeyAction n ell peSel seed flag).liftedOperation () sigma)
          ((FinalStage.aliceKeyAction n ell peSel seed flag).out.pairEquiv.symm (a, rB))
          ((FinalStage.aliceKeyAction n ell peSel seed flag).out.pairEquiv.symm (a', rB)) =
        ∑ rA : Fin (2 ^ n),
          if a = QKD.BB84.Model.aliceKeySlotOf n ell peSel seed flag rA ∧ a' =
            QKD.BB84.Model.aliceKeySlotOf n ell peSel seed flag rA then
            sigma ((TwoParty.pairEquiv _ _).symm (rA, rB))
              ((TwoParty.pairEquiv _ _).symm (rA, rB))
          else 0 := by
    change (((Instrument.functionAndForget (QKD.BB84.Model.aliceKeySlotOf n ell peSel seed
      flag)).liftAt
      (FinalStage.rawSystem n) .alice).operation () sigma)
        (((FinalStage.rawSystem n).set .alice
          (Fin (2 ^ ell))).pairEquiv.symm (a, rB))
        (((FinalStage.rawSystem n).set .alice
          (Fin (2 ^ ell))).pairEquiv.symm (a', rB)) = _
    rw [Instrument.liftAt_alice_operation_apply, Instrument.functionAndForget_operation_apply]
    rfl
  simp_rw [Matrix.submatrix_apply, hAliceApply]
  rfl

/-- Every entry of the key-discarding continuation is the trace of its input: its output space
is a single point. -/
private theorem discardKeys_denote_apply
    (n : ℕ) (sigma : TypedLOCC.Op (FinalStage.rawSystem n).total)
    (z z' : (Boundary.leaf FinalStage.abortSystem).space) :
    (FinalStage.discardKeys n).denote sigma z z' = ∑ x, sigma x x := by
  have hspace (u v : (Boundary.leaf FinalStage.abortSystem).space) : u = v := by
    rcases u with ⟨⟨⟩, u⟩
    rcases v with ⟨⟨⟩, v⟩
    congr
    funext i
    cases i <;> exact Unit.ext _ _
  have hzz : z = z' := hspace z z'
  subst z'
  have hp := Instrument.channel_trace_eq (FinalStage.discardKeys n).toInstrument sigma
  change (∑ x, (FinalStage.discardKeys n).denote sigma x x) = ∑ x, sigma x x at hp
  have hsum : (∑ x, (FinalStage.discardKeys n).denote sigma x x) =
      (FinalStage.discardKeys n).denote sigma z z := by
    apply Fintype.sum_eq_single z
    intro b hne
    exact (hne (hspace b z)).elim
  rw [hsum] at hp
  exact hp

/-- **Exact kernel of the final decision stage.**  Each output entry of the final-stage program
collects the raw diagonal entries whose final point `rawClassicalTailFinalPoint` equals both output
coordinates: the accept flag selects the key block or the abort block, and the key block is filled
by the two local key functions. -/
private theorem finalStage_program_denote_apply
    (n m ell ellEV : ℕ) (peSel xSel : Fin n → Bool) (leakEC : ℕ)
    (ec : ECScheme n peSel leakEC) (delta Q : ℝ)
    (d : QKD.BB84.ClassicalTailData n m ell ellEV peSel leakEC)
    (sigma : TypedLOCC.Op (FinalStage.rawSystem n).total)
    (p p' : (FinalStage.boundary ell).space) :
    (FinalStage.program n m ell ellEV peSel xSel leakEC ec delta Q
      d.alicePE d.bobPE d.seedPair d.evTag d.syndrome).denote sigma p p' =
      ∑ x, if rawClassicalTailFinalPoint n m ell ellEV peSel xSel leakEC ec delta Q
              d x = p ∧
            rawClassicalTailFinalPoint n m ell ellEV peSel xSel leakEC ec delta Q
              d x = p' then sigma x x else 0 := by
  let decisionOutput (d : QKD.BB84.ClassicalTailData n m ell ellEV peSel leakEC)
      (flag : Fin 2) :
      (FinalStage.decisionAnnouncement n m ellEV peSel xSel leakEC ec delta Q
        d.alicePE d.bobPE d.seedPair.2 d.evTag d.syndrome).out flag = FinalStage.rawSystem n := by
    simp only [FinalStage.decisionAnnouncement, AnnouncedAction.out_ofInstrument,
      FinalStage.rawSystem, TwoParty.set_bob]
    rfl
  let decisionOperation (d : QKD.BB84.ClassicalTailData n m ell ellEV peSel leakEC)
      (flag : Fin 2) (sigma : Op (FinalStage.rawSystem n).total) :=
    ((FinalStage.decisionAnnouncement n m ellEV peSel xSel leakEC ec delta Q
      d.alicePE d.bobPE d.seedPair.2 d.evTag d.syndrome).liftedOperation flag sigma).submatrix
        (Equiv.cast (congrArg MultipartiteSystem.total (decisionOutput d flag))).symm
        (Equiv.cast (congrArg MultipartiteSystem.total (decisionOutput d flag))).symm
  have hDecision
      (d : QKD.BB84.ClassicalTailData n m ell ellEV peSel leakEC)
      (sigma : Op (FinalStage.rawSystem n).total)
      (flag : Fin 2) (x x' : (FinalStage.rawSystem n).total) :
      decisionOperation d flag sigma x x' =
      if QKD.BB84.Model.acceptFlagOf n m ellEV peSel xSel leakEC ec delta Q
            d.alicePE d.bobPE d.seedPair.2 d.evTag d.syndrome (x .bob) = flag ∧
          QKD.BB84.Model.acceptFlagOf n m ellEV peSel xSel leakEC ec delta Q
            d.alicePE d.bobPE d.seedPair.2 d.evTag d.syndrome (x' .bob) = flag then
        sigma x x' else 0 := by
    change (FinalStage.decisionAnnouncement n m ellEV peSel xSel leakEC ec delta Q
      d.alicePE d.bobPE d.seedPair.2 d.evTag d.syndrome).liftedOperation flag sigma
        (cast (congrArg MultipartiteSystem.total ((FinalStage.rawSystem n).set_self .bob).symm) x)
        (cast (congrArg MultipartiteSystem.total
          ((FinalStage.rawSystem n).set_self .bob).symm) x') = _
    rw [← MultipartiteSystem.splitAtSet_self_symm, ← MultipartiteSystem.splitAtSet_self_symm]
    change ((Instrument.nondemolitionReadout (QKD.BB84.Model.acceptFlagOf
      n m ellEV peSel xSel leakEC ec delta Q d.alicePE d.bobPE d.seedPair.2
        d.evTag d.syndrome)).liftAt (FinalStage.rawSystem n) .bob).operation flag sigma
      (((FinalStage.rawSystem n).splitAtSet .bob (Fin (2 ^ n))).symm
        ((FinalStage.rawSystem n).splitAt .bob x))
      (((FinalStage.rawSystem n).splitAtSet .bob (Fin (2 ^ n))).symm
        ((FinalStage.rawSystem n).splitAt .bob x')) = _
    rw [Instrument.liftAt_operation_apply]
    simp only [Equiv.apply_symm_apply]
    simpa only [Matrix.submatrix_apply, Prod.eta, Equiv.symm_apply_apply] using
      Instrument.nondemolitionReadout_operation_apply
        (QKD.BB84.Model.acceptFlagOf n m ellEV peSel xSel leakEC ec delta Q
          d.alicePE d.bobPE d.seedPair.2 d.evTag d.syndrome) flag
        (sigma.submatrix
          (fun y => ((FinalStage.rawSystem n).splitAt .bob).symm
            (y, ((FinalStage.rawSystem n).splitAt .bob x).2))
          (fun y => ((FinalStage.rawSystem n).splitAt .bob).symm
            (y, ((FinalStage.rawSystem n).splitAt .bob x').2)))
        ((FinalStage.rawSystem n).splitAt .bob x).1
        ((FinalStage.rawSystem n).splitAt .bob x').1
  have hFinalAtFlag
      (d : QKD.BB84.ClassicalTailData n m ell ellEV peSel leakEC)
      (sigma : Op (FinalStage.rawSystem n).total) (flag : Fin 2)
      (u v : (FinalStage.flagBoundary ell flag).space) :
      (FinalStage.program n m ell ellEV peSel xSel leakEC ec delta Q
        d.alicePE d.bobPE d.seedPair d.evTag d.syndrome).denote sigma
          ((Boundary.publicSpaceEquiv (FinalStage.flagBoundary ell)).symm ⟨flag, u⟩)
          ((Boundary.publicSpaceEquiv (FinalStage.flagBoundary ell)).symm ⟨flag, v⟩) =
      (FinalStage.continuation n ell peSel leakEC ec d.seedPair.1 d.syndrome flag).denote
        (decisionOperation d flag sigma) u v := by
    unfold FinalStage.program
    have hblock := Program.denote_then_publicSpaceEquiv_symm_apply
      (FinalStage.decisionAnnouncement n m ellEV peSel xSel leakEC ec delta Q
        d.alicePE d.bobPE d.seedPair.2 d.evTag d.syndrome) (Equiv.refl _) (fun _ => rfl)
    simp only [FinalStage.decisionAnnouncement_announce] at hblock
    refine (hblock _ _ sigma flag u v).trans ?_
    rw [Program.denote_cast_apply (decisionOutput d flag) rfl]
    rfl
  have hPointAccept
      (d : QKD.BB84.ClassicalTailData n m ell ellEV peSel leakEC)
      (x : (FinalStage.rawSystem n).total)
      (hf : QKD.BB84.Model.acceptFlagOf n m ellEV peSel xSel leakEC ec delta Q
        d.alicePE d.bobPE d.seedPair.2 d.evTag d.syndrome (x .bob) = 0) :
      rawClassicalTailFinalPoint n m ell ellEV peSel xSel leakEC ec delta Q d x =
        (Boundary.publicSpaceEquiv (FinalStage.flagBoundary ell)).symm
          ⟨0, (Boundary.leafSpaceEquiv (FinalStage.keySystem ell)).symm
            ((TwoParty.pairEquiv _ _).symm
              (QKD.BB84.Model.aliceKeySlotOf n ell peSel d.seedPair.1 0 (x .alice),
               QKD.BB84.Model.bobKeySlotOf n ell peSel leakEC ec d.seedPair.1 d.syndrome
                 0 (x .bob)))⟩ := by
    apply (Boundary.publicSpaceEquiv (FinalStage.flagBoundary ell)).injective
    simp only [rawClassicalTailFinalPoint, hf, dif_pos, Equiv.apply_symm_apply]
    simp [hf, FinalStage.flagBoundary, Boundary.leafSpaceEquiv, TwoParty.pairEquiv]
  have hPointAbort
      (d : QKD.BB84.ClassicalTailData n m ell ellEV peSel leakEC)
      (x : (FinalStage.rawSystem n).total)
      (hf : QKD.BB84.Model.acceptFlagOf n m ellEV peSel xSel leakEC ec delta Q
        d.alicePE d.bobPE d.seedPair.2 d.evTag d.syndrome (x .bob) ≠ 0) :
      rawClassicalTailFinalPoint n m ell ellEV peSel xSel leakEC ec delta Q d x =
        (Boundary.publicSpaceEquiv (FinalStage.flagBoundary ell)).symm
          ⟨1, (Boundary.leafSpaceEquiv FinalStage.abortSystem).symm
            ((TwoParty.pairEquiv Unit Unit).symm ((), ()))⟩ := by
    have hone : QKD.BB84.Model.acceptFlagOf n m ellEV peSel xSel leakEC ec delta Q
        d.alicePE d.bobPE d.seedPair.2 d.evTag d.syndrome (x .bob) = 1 :=
      Fin.eq_one_of_ne_zero _ hf
    apply (Boundary.publicSpaceEquiv (FinalStage.flagBoundary ell)).injective
    simp [rawClassicalTailFinalPoint, hone, FinalStage.flagBoundary,
      Boundary.publicSpaceEquiv, Boundary.leafSpaceEquiv, TwoParty.pairEquiv]
  let keyPoint (a b : Fin (2 ^ ell)) : (FinalStage.boundary ell).space :=
    (Boundary.publicSpaceEquiv (FinalStage.flagBoundary ell)).symm
      ⟨0, (Boundary.leafSpaceEquiv (FinalStage.keySystem ell)).symm
        ((TwoParty.pairEquiv _ _).symm (a, b))⟩
  let abortPoint : (FinalStage.boundary ell).space :=
    (Boundary.publicSpaceEquiv (FinalStage.flagBoundary ell)).symm
      ⟨1, (Boundary.leafSpaceEquiv FinalStage.abortSystem).symm
        ((TwoParty.pairEquiv Unit Unit).symm ((), ()))⟩
  have hKeyPoint (a b a' b' : Fin (2 ^ ell)) :
      keyPoint a b = keyPoint a' b' ↔ a = a' ∧ b = b' := by
    constructor
    · intro h
      have hg := (Boundary.publicSpaceEquiv (FinalStage.flagBoundary ell)).symm.injective h
      have hl :
          (Boundary.leafSpaceEquiv (FinalStage.keySystem ell)).symm
              ((TwoParty.pairEquiv _ _).symm (a, b)) =
            (Boundary.leafSpaceEquiv (FinalStage.keySystem ell)).symm
              ((TwoParty.pairEquiv _ _).symm (a', b')) :=
        eq_of_heq (Sigma.mk.inj_iff.mp hg).2
      exact Prod.mk.inj ((TwoParty.pairEquiv _ _).symm.injective
        ((Boundary.leafSpaceEquiv (FinalStage.keySystem ell)).symm.injective hl))
    · rintro ⟨rfl, rfl⟩
      rfl
  have hKeyNeAbort (a b : Fin (2 ^ ell)) : keyPoint a b ≠ abortPoint := by
    intro h
    have he := congrArg
      (fun p : (FinalStage.boundary ell).space =>
        (Boundary.publicSpaceEquiv (FinalStage.flagBoundary ell) p).1) h
    change (0 : Fin 2) = 1 at he
    exact (by decide : (0 : Fin 2) ≠ 1) he
  have hPointKey
      (d : QKD.BB84.ClassicalTailData n m ell ellEV peSel leakEC)
      (x : (FinalStage.rawSystem n).total) (a b : Fin (2 ^ ell)) :
      rawClassicalTailFinalPoint n m ell ellEV peSel xSel leakEC ec delta Q d x =
          keyPoint a b ↔
        QKD.BB84.Model.acceptFlagOf n m ellEV peSel xSel leakEC ec delta Q
            d.alicePE d.bobPE d.seedPair.2 d.evTag d.syndrome (x .bob) = 0 ∧
          a = QKD.BB84.Model.aliceKeySlotOf n ell peSel d.seedPair.1 0 (x .alice) ∧
          b = QKD.BB84.Model.bobKeySlotOf n ell peSel leakEC ec d.seedPair.1 d.syndrome
            0 (x .bob) := by
    by_cases hf : QKD.BB84.Model.acceptFlagOf n m ellEV peSel xSel leakEC ec delta Q
        d.alicePE d.bobPE d.seedPair.2 d.evTag d.syndrome (x .bob) = 0
    · rw [hPointAccept d x hf]
      change keyPoint _ _ = keyPoint a b ↔ _
      rw [hKeyPoint]
      simp [hf, eq_comm]
    · rw [hPointAbort d x hf]
      change abortPoint = keyPoint a b ↔ _
      simp [hf, Ne.symm (hKeyNeAbort a b)]
  have hPointAbortIff
      (d : QKD.BB84.ClassicalTailData n m ell ellEV peSel leakEC)
      (x : (FinalStage.rawSystem n).total) :
      rawClassicalTailFinalPoint n m ell ellEV peSel xSel leakEC ec delta Q d x =
          abortPoint ↔
        QKD.BB84.Model.acceptFlagOf n m ellEV peSel xSel leakEC ec delta Q
          d.alicePE d.bobPE d.seedPair.2 d.evTag d.syndrome (x .bob) ≠ 0 := by
    by_cases hf : QKD.BB84.Model.acceptFlagOf n m ellEV peSel xSel leakEC ec delta Q
        d.alicePE d.bobPE d.seedPair.2 d.evTag d.syndrome (x .bob) = 0
    · rw [hPointAccept d x hf]
      change keyPoint _ _ = abortPoint ↔ _
      simp [hf, hKeyNeAbort]
    · rw [hPointAbort d x hf]
      change abortPoint = abortPoint ↔ _
      simp [hf]
  have hRawSum (g : (FinalStage.rawSystem n).total → ℂ) :
      (∑ x, g x) = ∑ b : Fin (2 ^ n), ∑ a : Fin (2 ^ n),
        g ((TwoParty.pairEquiv _ _).symm (a, b)) := by
    rw [← Equiv.sum_comp (TwoParty.pairEquiv (Fin (2 ^ n)) (Fin (2 ^ n))).symm]
    rw [Fintype.sum_prod_type, Finset.sum_comm]
  have hAbortSpace (z : (Boundary.leaf FinalStage.abortSystem).space) :
      z = (Boundary.leafSpaceEquiv FinalStage.abortSystem).symm
        ((TwoParty.pairEquiv Unit Unit).symm ((), ())) := by
    rcases z with ⟨⟨⟩, z⟩
    congr
    funext i
    cases i <;> exact Unit.ext _ _
  have hCont0 (seed : KeyHashSeed n ell peSel) (syn : Fin (2 ^ leakEC)) :
      FinalStage.continuation n ell peSel leakEC ec seed syn (0 : Fin 2) =
        FinalStage.acceptContinuation n ell peSel leakEC ec seed syn 0 := by
    simp [FinalStage.continuation, FinalStage.flagBoundary]
  have hCont1 (seed : KeyHashSeed n ell peSel) (syn : Fin (2 ^ leakEC)) :
      FinalStage.continuation n ell peSel leakEC ec seed syn (1 : Fin 2) =
        FinalStage.discardKeys n := by
    simp [FinalStage.continuation, FinalStage.flagBoundary]
  have hFinalKeys
      (d : QKD.BB84.ClassicalTailData n m ell ellEV peSel leakEC)
      (sigma : TypedLOCC.Op (FinalStage.rawSystem n).total)
      (a a' b b' : Fin (2 ^ ell)) :
      (FinalStage.program n m ell ellEV peSel xSel leakEC ec delta Q
        d.alicePE d.bobPE d.seedPair d.evTag d.syndrome).denote sigma
          (keyPoint a b) (keyPoint a' b') =
        ∑ x, if rawClassicalTailFinalPoint n m ell ellEV peSel xSel leakEC ec delta Q
                d x = keyPoint a b ∧
              rawClassicalTailFinalPoint n m ell ellEV peSel xSel leakEC ec delta Q
                d x = keyPoint a' b' then sigma x x else 0 := by
    conv_lhs => dsimp only [keyPoint]
    rw [hFinalAtFlag, hCont0]
    dsimp only [FinalStage.flagBoundary]
    refine (acceptContinuation_denote_apply n ell peSel leakEC ec d.seedPair.1 d.syndrome 0
      (decisionOperation d 0 sigma) a a' b b').trans ?_
    rw [hRawSum]
    apply Finset.sum_congr rfl
    intro y _
    by_cases hb : b = QKD.BB84.Model.bobKeySlotOf n ell peSel leakEC ec d.seedPair.1
          d.syndrome 0 y ∧
        b' = QKD.BB84.Model.bobKeySlotOf n ell peSel leakEC ec d.seedPair.1 d.syndrome 0 y
    · rw [if_pos hb]
      apply Finset.sum_congr rfl
      intro x _
      rw [hDecision d sigma (0 : Fin 2)]
      simp only [hPointKey d ((TwoParty.pairEquiv _ _).symm (x, y))]
      dsimp only [TwoParty.pairEquiv]
      by_cases ha : a = QKD.BB84.Model.aliceKeySlotOf n ell peSel d.seedPair.1 0 x <;>
        by_cases ha' : a' = QKD.BB84.Model.aliceKeySlotOf n ell peSel d.seedPair.1 0 x <;>
        by_cases hf : QKD.BB84.Model.acceptFlagOf n m ellEV peSel xSel leakEC ec
          delta Q d.alicePE d.bobPE d.seedPair.2 d.evTag d.syndrome y = 0 <;>
        simp [ha, ha', hf, hb.1, hb.2]
    · rw [if_neg hb]
      symm
      apply Finset.sum_eq_zero
      intro x _
      simp only [hPointKey d ((TwoParty.pairEquiv _ _).symm (x, y))]
      dsimp only [TwoParty.pairEquiv]
      apply if_neg
      intro hp
      exact hb ⟨hp.1.2.2, hp.2.2.2⟩
  have hFinalAbort
      (d : QKD.BB84.ClassicalTailData n m ell ellEV peSel leakEC)
      (sigma : TypedLOCC.Op (FinalStage.rawSystem n).total) :
      (FinalStage.program n m ell ellEV peSel xSel leakEC ec delta Q
        d.alicePE d.bobPE d.seedPair d.evTag d.syndrome).denote sigma abortPoint abortPoint =
        ∑ x, if rawClassicalTailFinalPoint n m ell ellEV peSel xSel leakEC ec delta Q
          d x = abortPoint then sigma x x else 0 := by
    conv_lhs => dsimp only [abortPoint]
    rw [hFinalAtFlag, hCont1]
    dsimp only [FinalStage.flagBoundary]
    refine (discardKeys_denote_apply n (decisionOperation d 1 sigma) _ _).trans ?_
    apply Finset.sum_congr rfl
    intro x _
    rw [hDecision d sigma (1 : Fin 2) x x]
    simp only [hPointAbortIff d x]
    have hf : (QKD.BB84.Model.acceptFlagOf n m ellEV peSel xSel leakEC ec delta Q
          d.alicePE d.bobPE d.seedPair.2 d.evTag d.syndrome (x .bob) = 1) ↔
        (QKD.BB84.Model.acceptFlagOf n m ellEV peSel xSel leakEC ec delta Q
          d.alicePE d.bobPE d.seedPair.2 d.evTag d.syndrome (x .bob) ≠ 0) := by
      constructor
      · intro h
        rw [h]
        decide
      · exact Fin.eq_one_of_ne_zero _
    simp only [and_self, hf]
  have hFinalSpace (p : (FinalStage.boundary ell).space) :
      (∃ a b : Fin (2 ^ ell), p = keyPoint a b) ∨ p = abortPoint := by
    obtain ⟨⟨flag, z⟩, rfl⟩ :=
      (Boundary.publicSpaceEquiv (FinalStage.flagBoundary ell)).symm.surjective p
    by_cases hf : flag = 0
    · subst flag
      change (Boundary.leaf (FinalStage.keySystem ell)).space at z
      obtain ⟨⟨a, b⟩, hz⟩ :=
        ((TwoParty.pairEquiv (Fin (2 ^ ell)) (Fin (2 ^ ell))).symm.trans
          (Boundary.leafSpaceEquiv (FinalStage.keySystem ell)).symm).surjective z
      exact Or.inl ⟨a, b, congrArg
        (fun w => (Boundary.publicSpaceEquiv (FinalStage.flagBoundary ell)).symm
          ⟨(0 : Fin 2), w⟩) hz.symm⟩
    · have hone : flag = 1 := Fin.eq_one_of_ne_zero _ hf
      subst flag
      rw [hAbortSpace z]
      exact Or.inr rfl
  have hFinalCross
      (d : QKD.BB84.ClassicalTailData n m ell ellEV peSel leakEC)
      (sigma : TypedLOCC.Op (FinalStage.rawSystem n).total) (a b : Fin (2 ^ ell)) :
      (FinalStage.program n m ell ellEV peSel xSel leakEC ec delta Q
        d.alicePE d.bobPE d.seedPair d.evTag d.syndrome).denote sigma
          (keyPoint a b) abortPoint = 0 ∧
      (FinalStage.program n m ell ellEV peSel xSel leakEC ec delta Q
        d.alicePE d.bobPE d.seedPair d.evTag d.syndrome).denote sigma
          abortPoint (keyPoint a b) = 0 := by
    constructor
    · exact Program.denote_public_block_zero
        (next := FinalStage.flagBoundary ell) _ sigma
        (by decide : (0 : Fin 2) ≠ 1) () () _ _
    · exact Program.denote_public_block_zero
        (next := FinalStage.flagBoundary ell) _ sigma
        (by decide : (1 : Fin 2) ≠ 0) () () _ _
  rcases hFinalSpace p with ⟨a, b, rfl⟩ | rfl <;>
    rcases hFinalSpace p' with ⟨a', b', rfl⟩ | rfl
  · exact hFinalKeys d sigma a a' b b'
  · rw [(hFinalCross d sigma a b).1]
    symm
    apply Finset.sum_eq_zero
    intro x _
    apply if_neg
    rintro ⟨hp, hp'⟩
    exact hKeyNeAbort a b (hp.symm.trans hp')
  · rw [(hFinalCross d sigma a' b').2]
    symm
    apply Finset.sum_eq_zero
    intro x _
    apply if_neg
    rintro ⟨hp, hp'⟩
    exact hKeyNeAbort a' b' (hp'.symm.trans hp)
  · simpa only [and_self] using hFinalAbort d sigma

/-- The fused announcement followed by termination, read on the diagonal: the announced tag and
syndrome must be those of Alice's raw register, with the uniform seed-pair weight. -/
private theorem fusedStage_done_denote_apply
    (n ell ellEV : ℕ) (peSel : Fin n → Bool) (leakEC : ℕ) (ec : ECScheme n peSel leakEC)
    (sigma : TypedLOCC.Op (FinalStage.rawSystem n).total)
    (x : (FinalStage.rawSystem n).total)
    (o : QKD.BB84.FusedPublic n ell ellEV peSel leakEC) :
    (QKD.BB84.fusedStage n ell ellEV peSel leakEC ec
      (fun _ => Program.done)).denote sigma
        ((Boundary.uniformSpaceEquiv (FinalStage.rawSystem n)
          (.cons (QKD.BB84.FusedPublic n ell ellEV peSel leakEC)
            .nil)).symm (x, (o, ())))
        ((Boundary.uniformSpaceEquiv (FinalStage.rawSystem n)
          (.cons (QKD.BB84.FusedPublic n ell ellEV peSel leakEC)
            .nil)).symm (x, (o, ()))) =
      if QKD.BB84.Model.evTagSynOf n ell ellEV peSel leakEC ec
            ((QKD.BB84.fusedPublicEquiv
              n ell ellEV peSel leakEC).symm o).1 (x .alice) =
          ((QKD.BB84.fusedPublicEquiv
            n ell ellEV peSel leakEC).symm o).2 then
        (Fintype.card (KeyHashSeedPairEV n ell ellEV peSel) : ℂ)⁻¹ * sigma x x
      else 0 := by
  let hout (y : QKD.BB84.FusedPublic n ell ellEV peSel leakEC) :
      (QKD.BB84.fusedAnnouncement n ell ellEV peSel leakEC ec).out y =
        FinalStage.rawSystem n := by
    simp only [QKD.BB84.fusedAnnouncement, AnnouncedAction.out_ofInstrument,
      FinalStage.rawSystem, TwoParty.set_alice]
  unfold QKD.BB84.fusedStage
  have hn := Program.denote_then_publicSpaceEquiv_symm_apply
    (QKD.BB84.fusedAnnouncement n ell ellEV peSel leakEC ec)
    (QKD.BB84.fusedPublicEquiv n ell ellEV peSel leakEC) (fun _ => rfl)
    (fun _ => Boundary.leaf (FinalStage.rawSystem n))
    (fun y => cast (congrArg (fun R => Program R (.leaf (FinalStage.rawSystem n)))
      (hout y).symm) Program.done) sigma
    ((QKD.BB84.fusedPublicEquiv n ell ellEV peSel leakEC).symm o)
    ((Boundary.leafSpaceEquiv (FinalStage.rawSystem n)).symm x)
    ((Boundary.leafSpaceEquiv (FinalStage.rawSystem n)).symm x)
  have hann : (QKD.BB84.fusedAnnouncement n ell ellEV peSel leakEC ec).announce
      ((QKD.BB84.fusedPublicEquiv n ell ellEV peSel leakEC).symm o) = o :=
    (QKD.BB84.fusedPublicEquiv n ell ellEV peSel leakEC).apply_symm_apply o
  rw [hann] at hn
  refine hn.trans ?_
  rw [Program.denote_cast_apply (hout o) rfl, Program.denote_done]
  change (QKD.BB84.fusedAnnouncement n ell ellEV peSel leakEC ec).liftedOperation
    ((QKD.BB84.fusedPublicEquiv n ell ellEV peSel leakEC).symm o) sigma
      (cast (congrArg MultipartiteSystem.total
        ((FinalStage.rawSystem n).set_self .alice).symm) x)
      (cast (congrArg MultipartiteSystem.total
        ((FinalStage.rawSystem n).set_self .alice).symm) x) = _
  rw [← MultipartiteSystem.splitAtSet_self_symm]
  have hop := QKD.BB84.fusedAnnouncement_liftedOperation_apply n ell ellEV peSel leakEC ec
    ((QKD.BB84.fusedPublicEquiv n ell ellEV peSel leakEC).symm o).1
    ((QKD.BB84.fusedPublicEquiv n ell ellEV peSel leakEC).symm o).2 sigma x x
  simpa only [and_self, Fintype.card_fin] using hop

/-- One PE-bit readout, on the diagonal: the announced bit must be the reader's register bit. -/
private theorem peBitAnnouncement_liftedOperation_diag
    (n : ℕ) (i : Fin n) (actor : Party) (o : Fin 2)
    (sigma : TypedLOCC.Op (FinalStage.rawSystem n).total)
    (x : (FinalStage.rawSystem n).total) :
    (QKD.BB84.peBitAnnouncement n i actor).liftedOperation
        (LOCC.outcomeDigit 2 o) sigma
        (cast (congrArg MultipartiteSystem.total
          ((FinalStage.rawSystem n).set_self actor).symm) x)
        (cast (congrArg MultipartiteSystem.total
          ((FinalStage.rawSystem n).set_self actor).symm) x) =
      if QKD.BB84.localRegisterBit n i actor (x actor) =
          LOCC.outcomeDigit 2 o then sigma x x else 0 := by
  rw [← MultipartiteSystem.splitAtSet_self_symm (FinalStage.rawSystem n) actor]
  simpa only [and_self] using
    QKD.BB84.peBitAnnouncement_liftedOperation_apply n i actor
      (LOCC.outcomeDigit 2 o) sigma x x

/-- The PE announcement loop over `r` rounds followed by the fused stage, read on the diagonal:
every announced PE bit must be the corresponding register bit, and the fused announcement must
match Alice's raw register. -/
private theorem peAnnouncementLoop_denote_diag
    (n ell ellEV : ℕ) (peSel : Fin n → Bool) (leakEC : ℕ) (ec : ECScheme n peSel leakEC)
    (r : ℕ) (idx : Fin r → Fin n)
    (sigma : TypedLOCC.Op (FinalStage.rawSystem n).total)
    (x : (FinalStage.rawSystem n).total)
    (raw : QKD.BB84.PreDecisionRaw r
      (QKD.BB84.Model.bb84AnnounceCard n ell ellEV peSel leakEC)) :
    (QKD.BB84.peAnnouncementLoop n
      (T := .cons (QKD.BB84.FusedPublic
        n ell ellEV peSel leakEC) .nil) r idx
      (fun _ _ => QKD.BB84.fusedStage
        n ell ellEV peSel leakEC ec (fun _ => Program.done))).denote sigma
        ((Boundary.uniformSpaceEquiv (FinalStage.rawSystem n)
          (PE.transcriptWord r
            (.cons (QKD.BB84.FusedPublic n ell ellEV peSel leakEC)
              .nil))).symm
          (x, (QKD.BB84.preDecisionRawEquiv r
            (QKD.BB84.Model.bb84AnnounceCard n ell ellEV peSel leakEC)).symm raw))
        ((Boundary.uniformSpaceEquiv (FinalStage.rawSystem n)
          (PE.transcriptWord r
            (.cons (QKD.BB84.FusedPublic n ell ellEV peSel leakEC)
              .nil))).symm
          (x, (QKD.BB84.preDecisionRawEquiv r
            (QKD.BB84.Model.bb84AnnounceCard n ell ellEV peSel leakEC)).symm raw)) =
      if (∀ j, LOCC.registerBit n (idx j) (x .bob) =
            LOCC.outcomeDigit 2 (raw.bobPERaw j)) ∧
          (∀ j, LOCC.registerBit n (idx j) (x .alice) =
            LOCC.outcomeDigit 2 (raw.alicePERaw j)) ∧
          QKD.BB84.Model.evTagSynOf n ell ellEV peSel leakEC ec
              ((QKD.BB84.fusedPublicEquiv
                n ell ellEV peSel leakEC).symm raw.fusedRaw).1 (x .alice) =
            ((QKD.BB84.fusedPublicEquiv
              n ell ellEV peSel leakEC).symm raw.fusedRaw).2 then
        (Fintype.card (KeyHashSeedPairEV n ell ellEV peSel) : ℂ)⁻¹ * sigma x x
      else 0 := by
  induction r generalizing sigma with
  | zero =>
    rcases raw with ⟨bs, as, fused⟩
    -- With no PE rounds left only the fused announcement acts, and both PE tests are vacuous.
    simp only [IsEmpty.forall_iff, true_and]
    exact fusedStage_done_denote_apply n ell ellEV peSel leakEC ec sigma x fused
  | succ r ih =>
    rcases raw with ⟨bs, as, fused⟩
    rw [QKD.BB84.peAnnouncementLoop_succ]
    have hBob := fun k rho => Program.denote_then_publicSpaceEquiv_symm_apply
      (QKD.BB84.bobPEBitAnnouncement n (idx 0)) (LOCC.outcomeDigit 2).symm (fun _ => rfl)
      (fun _ => Boundary.uniform (FinalStage.rawSystem n)
        (.cons (Fin 2) (PE.transcriptWord r
          (.cons (QKD.BB84.FusedPublic n ell ellEV peSel leakEC) .nil))))
      k rho (LOCC.outcomeDigit 2 (bs 0))
    have hannBob : (QKD.BB84.bobPEBitAnnouncement n (idx 0)).announce
        (LOCC.outcomeDigit 2 (bs 0)) = bs 0 := (LOCC.outcomeDigit 2).symm_apply_apply _
    simp only [hannBob] at hBob
    refine (hBob _ sigma _ _).trans ?_
    refine (Program.denote_cast_apply ((FinalStage.rawSystem n).set_self .bob)
      rfl _ _ _ _).trans ?_
    simp only [Equiv.cast_refl, Equiv.refl_apply]
    have hAlice := fun k rho => Program.denote_then_publicSpaceEquiv_symm_apply
      (QKD.BB84.alicePEBitAnnouncement n (idx 0)) (LOCC.outcomeDigit 2).symm (fun _ => rfl)
      (fun _ => Boundary.uniform (FinalStage.rawSystem n)
        (PE.transcriptWord r (.cons (QKD.BB84.FusedPublic n ell ellEV peSel leakEC) .nil)))
      k rho (LOCC.outcomeDigit 2 (as 0))
    have hannAlice : (QKD.BB84.alicePEBitAnnouncement n (idx 0)).announce
        (LOCC.outcomeDigit 2 (as 0)) = as 0 := (LOCC.outcomeDigit 2).symm_apply_apply _
    simp only [hannAlice] at hAlice
    refine (hAlice _ _ _ _).trans ?_
    refine (Program.denote_cast_apply ((FinalStage.rawSystem n).set_self .alice)
      rfl _ _ _ _).trans ?_
    simp only [Equiv.cast_refl, Equiv.refl_apply]
    refine (ih (fun j => idx j.succ) _
      { bobPERaw := Fin.tail bs, alicePERaw := Fin.tail as, fusedRaw := fused }).trans ?_
    dsimp only [QKD.BB84.alicePEBitAnnouncement, QKD.BB84.bobPEBitAnnouncement]
    simp only [Matrix.reindex_apply, Matrix.submatrix_apply, ← Equiv.cast_symm,
      Equiv.cast_apply]
    rw [peBitAnnouncement_liftedOperation_diag n (idx 0) .alice (as 0)]
    simp only [Matrix.submatrix_apply, Equiv.cast_apply]
    rw [peBitAnnouncement_liftedOperation_diag n (idx 0) .bob (bs 0)]
    dsimp only [QKD.BB84.localRegisterBit]
    -- Split both tests over `Fin (r + 1)` into round `0` and the later rounds, then decide the
    -- two round-`0` readouts.
    simp only [Fin.forall_fin_succ, Fin.tail]
    by_cases hb : LOCC.registerBit n (idx 0) (x .bob) =
        LOCC.outcomeDigit 2 (bs 0) <;>
      by_cases ha : LOCC.registerBit n (idx 0) (x .alice) =
        LOCC.outcomeDigit 2 (as 0) <;>
      simp only [hb, ha, true_and, false_and, and_false, if_true, if_false, mul_zero, ite_self]

/-- Exact complete-output kernel of the actual retained classical tail.

The tail dephases both raw registers when they are finally converted to keys or discarded. Every
raw diagonal is pushed to the explicit PE/fused/final output point, with exactly the uniform seed
weight. The statement holds for arbitrary complex operators and all finite parameter sizes. -/
theorem rawClassicalTailProgram_output_apply
    (n m ell ellEV : ℕ) (peSel xSel : Fin n → Bool) (leakEC : ℕ)
    (ec : ECScheme n peSel leakEC) (delta Q : ℝ)
    (rho : TypedLOCC.Op (FinalStage.rawSystem n).total)
    (q q' : (QKD.BB84.rawClassicalTailBoundary n m ell ellEV peSel leakEC).space) :
    (QKD.BB84.rawClassicalTailProgram n m ell ellEV peSel xSel leakEC ec delta Q).denote rho q q' =
      if q = q' then
        ∑ x : (FinalStage.rawSystem n).total,
          ∑ st : KeyHashSeedPairEV n ell ellEV peSel,
            if rawClassicalTailOutputPoint n m ell ellEV peSel xSel leakEC ec
                delta Q x st = q then
              (Fintype.card (KeyHashSeedPairEV n ell ellEV peSel) : ℂ)⁻¹ *
                rho x x
            else 0
      else 0 := by
  classical
  have hDataEq
      (d : QKD.BB84.ClassicalTailData n m ell ellEV peSel leakEC)
      (x : (FinalStage.rawSystem n).total) :
      rawClassicalTailDataOf n m ell ellEV peSel leakEC ec x d.seedPair = d ↔
        (∀ j, LOCC.registerBit n (bb84PERoundIdx (m := m) peSel j) (x .bob) =
            d.bobPE j) ∧
          (∀ j, LOCC.registerBit n (bb84PERoundIdx (m := m) peSel j)
            (x .alice) = d.alicePE j) ∧
          QKD.BB84.Model.evTagSynOf n ell ellEV peSel leakEC ec
              (Fintype.equivFin (KeyHashSeedPairEV n ell ellEV peSel) d.seedPair)
              (x .alice) = finProdFinEquiv (d.evTag, d.syndrome) := by
    constructor
    · intro hd
      refine ⟨congrFun (congrArg QKD.BB84.ClassicalTailData.bobPE hd),
        congrFun (congrArg QKD.BB84.ClassicalTailData.alicePE hd), ?_⟩
      have hp :
          finProdFinEquiv.symm
              (QKD.BB84.Model.evTagSynOf n ell ellEV peSel leakEC ec
                (Fintype.equivFin (KeyHashSeedPairEV n ell ellEV peSel) d.seedPair)
                (x .alice)) = (d.evTag, d.syndrome) :=
        Prod.ext (congrArg QKD.BB84.ClassicalTailData.evTag hd)
          (congrArg QKD.BB84.ClassicalTailData.syndrome hd)
      exact (Equiv.symm_apply_eq _).mp hp
    · rintro ⟨hb, ha, hv⟩
      cases d
      dsimp only at hb ha hv
      simp only [rawClassicalTailDataOf, hv, Equiv.symm_apply_apply]
      congr 1
      · exact funext ha
      · exact funext hb
  have hPre
      (sigma : TypedLOCC.Op (FinalStage.rawSystem n).total)
      (d : QKD.BB84.ClassicalTailData n m ell ellEV peSel leakEC)
      (x : (FinalStage.rawSystem n).total) :
      (QKD.BB84.directPreDecisionProgram n m ell ellEV peSel leakEC ec).denote sigma
          ((Boundary.uniformSpaceEquiv (FinalStage.rawSystem n)
            (QKD.BB84.classicalTailWord n m ell ellEV peSel leakEC)).symm
            (x, (QKD.BB84.classicalTailDataEquiv n m ell ellEV peSel leakEC).symm d))
          ((Boundary.uniformSpaceEquiv (FinalStage.rawSystem n)
            (QKD.BB84.classicalTailWord n m ell ellEV peSel leakEC)).symm
            (x, (QKD.BB84.classicalTailDataEquiv n m ell ellEV peSel leakEC).symm d)) =
        if rawClassicalTailDataOf n m ell ellEV peSel leakEC ec x d.seedPair = d then
          (Fintype.card (KeyHashSeedPairEV n ell ellEV peSel) : ℂ)⁻¹ * sigma x x
        else 0 := by
    unfold QKD.BB84.directPreDecisionProgram
    refine (peAnnouncementLoop_denote_diag n ell ellEV peSel leakEC ec
      (n - bb84KeyRoundCount n m) (bb84PERoundIdx (m := m) peSel) sigma x
      ((QKD.BB84.classicalTailRawDataEquiv n m ell ellEV peSel leakEC).symm d)).trans ?_
    simp only [QKD.BB84.classicalTailRawDataEquiv, Equiv.coe_fn_symm_mk,
      Equiv.symm_apply_apply, Equiv.apply_symm_apply]
    simp only [hDataEq d x]
  have hUniformDenote
      (R : MultipartiteSystem Party) (T : TList) (D : Boundary Party) (p : Program R D)
      (e : (Boundary.uniform R T).Exit)
      (sigma : TypedLOCC.Op ((Boundary.uniform R T).system e).total)
      (a b : D.space) :
      (show Program ((Boundary.uniform R T).system e) D from
        by simpa only [Boundary.uniform_system] using p).denote sigma a b =
        p.denote (Matrix.reindex (Boundary.uniformSystemEquiv R T e)
          (Boundary.uniformSystemEquiv R T e) sigma) a b := by
    induction T with
    | nil => rfl
    | @cons Pub _ _ T ih => exact ih e.2 sigma
  have hUniformPoint
      (R : MultipartiteSystem Party) (T : TList) (e : (Boundary.uniform R T).Exit)
      (x : R.total) :
      (Boundary.uniformSpaceEquiv R T).symm
          (x, Boundary.uniformExitEquiv R T e) =
        ⟨e, (Boundary.uniformSystemEquiv R T e).symm x⟩ := by
    apply (Boundary.uniformSpaceEquiv R T).injective
    apply Prod.ext
    · simp only [Equiv.apply_symm_apply, Boundary.uniformSpaceEquiv_fst]
    · simp only [Equiv.apply_symm_apply, Boundary.uniformSpaceEquiv_snd]
  have hExtract (B : Boundary Party) (e : B.Exit)
      (sigma : TypedLOCC.Op B.space) (x x' : (B.system e).total) :
      ((Boundary.exitKraus B e)ᴴ * sigma * Boundary.exitKraus B e) x x' =
        sigma ⟨e, x⟩ ⟨e, x'⟩ := by
    -- Column `x` of `exitKraus B e` is the basis vector at `⟨e, x⟩`.
    simp [Matrix.mul_apply, Matrix.conjTranspose_apply, Boundary.exitKraus_apply]
  have hPreExit
      (e : (QKD.BB84.classicalPreDecisionBoundary n m ell ellEV peSel leakEC).Exit)
      (x : (FinalStage.rawSystem n).total) :
      Matrix.reindex
          (Boundary.uniformSystemEquiv (FinalStage.rawSystem n)
            (QKD.BB84.classicalTailWord n m ell ellEV peSel leakEC) e)
          (Boundary.uniformSystemEquiv (FinalStage.rawSystem n)
            (QKD.BB84.classicalTailWord n m ell ellEV peSel leakEC) e)
          ((Boundary.exitKraus
              (QKD.BB84.classicalPreDecisionBoundary n m ell ellEV peSel leakEC) e)ᴴ *
            (QKD.BB84.directPreDecisionProgram n m ell ellEV peSel leakEC ec).denote rho *
            Boundary.exitKraus
              (QKD.BB84.classicalPreDecisionBoundary n m ell ellEV peSel leakEC) e) x x =
        if rawClassicalTailDataOf n m ell ellEV peSel leakEC ec x
              (QKD.BB84.classicalTailExitEquiv n m ell ellEV peSel leakEC e).seedPair =
            QKD.BB84.classicalTailExitEquiv n m ell ellEV peSel leakEC e then
          (Fintype.card (KeyHashSeedPairEV n ell ellEV peSel) : ℂ)⁻¹ * rho x x
        else 0 := by
    simp only [Matrix.reindex_apply, Matrix.submatrix_apply]
    rw [hExtract]
    rw [← hUniformPoint (FinalStage.rawSystem n)
      (QKD.BB84.classicalTailWord n m ell ellEV peSel leakEC) e x]
    have ht : Boundary.uniformExitEquiv (FinalStage.rawSystem n)
          (QKD.BB84.classicalTailWord n m ell ellEV peSel leakEC) e =
        (QKD.BB84.classicalTailDataEquiv n m ell ellEV peSel leakEC).symm
          (QKD.BB84.classicalTailExitEquiv n m ell ellEV peSel leakEC e) := by
      exact ((QKD.BB84.classicalTailDataEquiv n m ell ellEV peSel leakEC).symm_apply_apply _).symm
    rw [ht]
    exact hPre rho (QKD.BB84.classicalTailExitEquiv n m ell ellEV peSel leakEC e) x
  have hTailSame
      (e : (QKD.BB84.classicalPreDecisionBoundary n m ell ellEV peSel leakEC).Exit)
      (a b : (FinalStage.boundary ell).space) :
      (QKD.BB84.rawClassicalTailProgram n m ell ellEV peSel xSel leakEC ec delta Q).denote rho
          ((Boundary.graftSpaceEquiv
            (QKD.BB84.classicalPreDecisionBoundary n m ell ellEV peSel leakEC)
            (fun _ => FinalStage.boundary ell)).symm ⟨e, a⟩)
          ((Boundary.graftSpaceEquiv
            (QKD.BB84.classicalPreDecisionBoundary n m ell ellEV peSel leakEC)
            (fun _ => FinalStage.boundary ell)).symm ⟨e, b⟩) =
        ∑ x, if rawClassicalTailFinalPoint n m ell ellEV peSel xSel leakEC ec delta Q
                (QKD.BB84.classicalTailExitEquiv n m ell ellEV peSel leakEC e) x = a ∧
              rawClassicalTailFinalPoint n m ell ellEV peSel xSel leakEC ec delta Q
                (QKD.BB84.classicalTailExitEquiv n m ell ellEV peSel leakEC e) x = b then
            if rawClassicalTailDataOf n m ell ellEV peSel leakEC ec x
                  (QKD.BB84.classicalTailExitEquiv n m ell ellEV peSel leakEC e).seedPair =
                QKD.BB84.classicalTailExitEquiv n m ell ellEV peSel leakEC e then
              (Fintype.card (KeyHashSeedPairEV n ell ellEV peSel) : ℂ)⁻¹ * rho x x
            else 0
          else 0 := by
    unfold QKD.BB84.rawClassicalTailProgram
    rw [Program.denote_graft]
    dsimp only [QKD.BB84.rawClassicalTailBoundary]
    simp only [LinearMap.comp_apply]
    rw [Program.controlledContinuation_sameExit]
    rw [hUniformDenote (FinalStage.rawSystem n)
      (QKD.BB84.classicalTailWord n m ell ellEV peSel leakEC)]
    rw [finalStage_program_denote_apply]
    simp only [hPreExit]
  have hOutputPoint
      (e : (QKD.BB84.classicalPreDecisionBoundary n m ell ellEV peSel leakEC).Exit)
      (a : (FinalStage.boundary ell).space)
      (x : (FinalStage.rawSystem n).total)
      (st : KeyHashSeedPairEV n ell ellEV peSel) :
      rawClassicalTailOutputPoint n m ell ellEV peSel xSel leakEC ec delta Q x st =
          (Boundary.graftSpaceEquiv
            (QKD.BB84.classicalPreDecisionBoundary n m ell ellEV peSel leakEC)
            (fun _ => FinalStage.boundary ell)).symm ⟨e, a⟩ ↔
        rawClassicalTailDataOf n m ell ellEV peSel leakEC ec x st =
            QKD.BB84.classicalTailExitEquiv n m ell ellEV peSel leakEC e ∧
          rawClassicalTailFinalPoint n m ell ellEV peSel xSel leakEC ec delta Q
            (QKD.BB84.classicalTailExitEquiv n m ell ellEV peSel leakEC e) x = a := by
    dsimp only [rawClassicalTailOutputPoint]
    constructor
    · intro hp
      have hs := (Boundary.graftSpaceEquiv
        (QKD.BB84.classicalPreDecisionBoundary n m ell ellEV peSel leakEC)
        (fun _ => FinalStage.boundary ell)).symm.injective hp
      have he := congrArg Sigma.fst hs
      have hd : rawClassicalTailDataOf n m ell ellEV peSel leakEC ec x st =
          QKD.BB84.classicalTailExitEquiv n m ell ellEV peSel leakEC e :=
        (Equiv.symm_apply_eq _).mp he
      have ha :
          rawClassicalTailFinalPoint n m ell ellEV peSel xSel leakEC ec delta Q
            (rawClassicalTailDataOf n m ell ellEV peSel leakEC ec x st) x = a :=
        eq_of_heq (Sigma.mk.inj_iff.mp hs).2
      exact ⟨hd, by rwa [hd] at ha⟩
    · rintro ⟨hd, ha⟩
      simp only [hd, Equiv.symm_apply_apply, ha]
  have hSeedSum
      (e : (QKD.BB84.classicalPreDecisionBoundary n m ell ellEV peSel leakEC).Exit)
      (a b : (FinalStage.boundary ell).space) (x : (FinalStage.rawSystem n).total) :
      (∑ st : KeyHashSeedPairEV n ell ellEV peSel,
        if rawClassicalTailOutputPoint n m ell ellEV peSel xSel leakEC ec delta Q x st =
              (Boundary.graftSpaceEquiv
                (QKD.BB84.classicalPreDecisionBoundary n m ell ellEV peSel leakEC)
                (fun _ => FinalStage.boundary ell)).symm ⟨e, a⟩ ∧
            rawClassicalTailOutputPoint n m ell ellEV peSel xSel leakEC ec delta Q x st =
              (Boundary.graftSpaceEquiv
                (QKD.BB84.classicalPreDecisionBoundary n m ell ellEV peSel leakEC)
                (fun _ => FinalStage.boundary ell)).symm ⟨e, b⟩ then
          (Fintype.card (KeyHashSeedPairEV n ell ellEV peSel) : ℂ)⁻¹ * rho x x
        else 0) =
      if rawClassicalTailFinalPoint n m ell ellEV peSel xSel leakEC ec delta Q
            (QKD.BB84.classicalTailExitEquiv n m ell ellEV peSel leakEC e) x = a ∧
          rawClassicalTailFinalPoint n m ell ellEV peSel xSel leakEC ec delta Q
            (QKD.BB84.classicalTailExitEquiv n m ell ellEV peSel leakEC e) x = b then
        if rawClassicalTailDataOf n m ell ellEV peSel leakEC ec x
              (QKD.BB84.classicalTailExitEquiv n m ell ellEV peSel leakEC e).seedPair =
            QKD.BB84.classicalTailExitEquiv n m ell ellEV peSel leakEC e then
          (Fintype.card (KeyHashSeedPairEV n ell ellEV peSel) : ℂ)⁻¹ * rho x x
        else 0
      else 0 := by
    rw [Fintype.sum_eq_single
      (QKD.BB84.classicalTailExitEquiv n m ell ellEV peSel leakEC e).seedPair]
    · -- Both output tests contain the same data test; decide it.
      simp only [hOutputPoint e]
      by_cases hd : rawClassicalTailDataOf n m ell ellEV peSel leakEC ec x
            (QKD.BB84.classicalTailExitEquiv n m ell ellEV peSel leakEC e).seedPair =
          QKD.BB84.classicalTailExitEquiv n m ell ellEV peSel leakEC e <;>
        simp [hd]
    · intro st hst
      apply if_neg
      rintro ⟨hp, _⟩
      have hd := (hOutputPoint e a x st).mp hp
      exact hst (congrArg QKD.BB84.ClassicalTailData.seedPair hd.1)
  have hTailJoint
      (e f : (QKD.BB84.classicalPreDecisionBoundary n m ell ellEV peSel leakEC).Exit)
      (a b : (FinalStage.boundary ell).space) :
      (QKD.BB84.rawClassicalTailProgram n m ell ellEV peSel xSel leakEC ec delta Q).denote rho
          ((Boundary.graftSpaceEquiv
            (QKD.BB84.classicalPreDecisionBoundary n m ell ellEV peSel leakEC)
            (fun _ => FinalStage.boundary ell)).symm ⟨e, a⟩)
          ((Boundary.graftSpaceEquiv
            (QKD.BB84.classicalPreDecisionBoundary n m ell ellEV peSel leakEC)
            (fun _ => FinalStage.boundary ell)).symm ⟨f, b⟩) =
        ∑ x : (FinalStage.rawSystem n).total,
          ∑ st : KeyHashSeedPairEV n ell ellEV peSel,
            if rawClassicalTailOutputPoint n m ell ellEV peSel xSel leakEC ec delta Q x st =
                  (Boundary.graftSpaceEquiv
                    (QKD.BB84.classicalPreDecisionBoundary n m ell ellEV peSel leakEC)
                    (fun _ => FinalStage.boundary ell)).symm ⟨e, a⟩ ∧
                rawClassicalTailOutputPoint n m ell ellEV peSel xSel leakEC ec delta Q x st =
                  (Boundary.graftSpaceEquiv
                    (QKD.BB84.classicalPreDecisionBoundary n m ell ellEV peSel leakEC)
                    (fun _ => FinalStage.boundary ell)).symm ⟨f, b⟩ then
              (Fintype.card (KeyHashSeedPairEV n ell ellEV peSel) : ℂ)⁻¹ * rho x x
            else 0 := by
    by_cases hef : e = f
    · subst f
      rw [hTailSame]
      apply Finset.sum_congr rfl
      intro x _
      exact (hSeedSum e a b x).symm
    · unfold QKD.BB84.rawClassicalTailProgram
      rw [Program.denote_graft]
      dsimp only [QKD.BB84.rawClassicalTailBoundary]
      simp only [LinearMap.comp_apply]
      rw [Program.controlledContinuation_block_zero _ _ hef]
      symm
      apply Finset.sum_eq_zero
      intro x _
      apply Finset.sum_eq_zero
      intro st _
      apply if_neg
      rintro ⟨hp, hp'⟩
      have he := (hOutputPoint e a x st).mp hp
      have hf := (hOutputPoint f b x st).mp hp'
      exact hef ((QKD.BB84.classicalTailExitEquiv n m ell ellEV peSel leakEC).injective
        (he.1.symm.trans hf.1))
  obtain ⟨⟨e, a⟩, rfl⟩ :=
    (Boundary.graftSpaceEquiv
      (QKD.BB84.classicalPreDecisionBoundary n m ell ellEV peSel leakEC)
      (fun _ => FinalStage.boundary ell)).symm.surjective q
  obtain ⟨⟨f, b⟩, rfl⟩ :=
    (Boundary.graftSpaceEquiv
      (QKD.BB84.classicalPreDecisionBoundary n m ell ellEV peSel leakEC)
      (fun _ => FinalStage.boundary ell)).symm.surjective q'
  rw [hTailJoint]
  by_cases hq :
      (Boundary.graftSpaceEquiv
        (QKD.BB84.classicalPreDecisionBoundary n m ell ellEV peSel leakEC)
        (fun _ => FinalStage.boundary ell)).symm ⟨e, a⟩ =
      (Boundary.graftSpaceEquiv
        (QKD.BB84.classicalPreDecisionBoundary n m ell ellEV peSel leakEC)
        (fun _ => FinalStage.boundary ell)).symm ⟨f, b⟩
  · rw [if_pos hq]
    simp only [← hq, and_self]
  · rw [if_neg hq]
    apply Finset.sum_eq_zero
    intro x _
    apply Finset.sum_eq_zero
    intro st _
    apply if_neg
    rintro ⟨hp, hp'⟩
    exact hq (hp.symm.trans hp')

/-- Internal nonzero-dimension evidence for the explicit complete tail boundary. -/
def rawClassicalTailBoundaryCardNeZero
    (n m ell ellEV : ℕ) (peSel : Fin n → Bool) (leakEC : ℕ) :
    NeZero (Fintype.card
      (QKD.BB84.rawClassicalTailBoundary n m ell ellEV peSel leakEC).space) := by
  let d : QKD.BB84.ClassicalTailData n m ell ellEV peSel leakEC :=
    { alicePE := fun _ => 0
      bobPE := fun _ => 0
      seedPair := (fun _ _ => 0, fun _ _ => 0)
      evTag := 0
      syndrome := 0 }
  let outer := (QKD.BB84.classicalTailExitEquiv n m ell ellEV peSel leakEC).symm d
  let final : (FinalStage.boundary ell).space :=
    (Boundary.publicSpaceEquiv (FinalStage.flagBoundary ell)).symm
      ⟨1, (Boundary.leafSpaceEquiv FinalStage.abortSystem).symm
        ((TwoParty.pairEquiv Unit Unit).symm ((), ()))⟩
  let q : (QKD.BB84.rawClassicalTailBoundary n m ell ellEV peSel leakEC).space :=
    (Boundary.graftSpaceEquiv
      (QKD.BB84.classicalPreDecisionBoundary n m ell ellEV peSel leakEC)
      (fun _ => FinalStage.boundary ell)).symm ⟨outer, final⟩
  exact ⟨@Fintype.card_ne_zero _ _ ⟨q⟩⟩

attribute [local instance] rawClassicalTailBoundaryCardNeZero

end QKD.BB84.Reduction
