import QCryptLean.QKD.BB84.Engine.PrivacyAmplification.B19Bridge
import QCryptLean.QKD.BB84.Engine.Budgets.BellPolyDimTight
import QCryptLean.Quantum.Symmetry.BellDeFinettiDomination
import QCryptLean.InfoTheory.DeFinetti.Purification

/-!
# Bell de Finetti purification reference

The full CKR postselection factor for BB84 is `(n+1)^{d²-1} = (n+1)^{15}` (the symmetric subspace
of `(ℂ⁴)^{⊗n}`, dimension exponent `d²-1 = 15`).  Because the BB84 attacked state is jointly
Bell-diagonal after the Bell twirl, it is supported on the **Bell-diagonal** symmetric subspace
generated by the four commuting Bell projectors, whose dimension is `C(n+3,3) ≤ (n+1)^{3}` — the
`d_Bell = 4` symmetric-subspace count `C(n + d_Bell - 1, d_Bell - 1)`. This is the tighter
postselection register the Bell-tightened CKR reduction is built on. The scalar dimension
`bb84PolyDimTight` itself is a pure combinatorial budget (`Engine/Budgets/BellPolyDimTight.lean`);
this file builds the quantum purification reference at that dimension.

## Main definitions and results

* `bb84BellCKRDeFinettiPurification` — the explicit square-root/vectorization
  purification of `bb84BellDeFinettiDensity`.
* `IsBellCKRDeFinettiPurification` — the Bell analogue of `IsCKRDeFinettiPurification`
  (pure, with `4^n` marginal equal to `bb84BellDeFinettiDensity`).
* `bb84BellCKRDeFinettiPurification_isPurification` — the explicit purification satisfies it.

## References

Nahar, Tupkary, Zhao, Lütkenhaus, Tan 2024 (`arXiv:2403.11851`) Thm 3, Lemma 2 (`x = 4`, joint
Bell `ℤ₂×ℤ₂` symmetry); CKR 2009 (`arXiv:0809.3019`) `main.tex:268`–`:401` (Main Result: Theorem
`\label{thm:main}` :291–:301, Lemma `\label{lem:extractpart}` :319–:328); Renner 2005 §6.5.  The
Bell de Finetti reference object `τ_Bell` is `Quantum.Symmetry.bb84BellDeFinettiState`
(`bb84_bellSym_deFinetti_domination`).
-/

open Quantum.Operators Quantum.TensorProducts Matrix Quantum.Channels
open InfoTheory.SmoothMinEntropy Math.ClassicalEntropy Quantum.Symmetry InfoTheory.DeFinetti

noncomputable section

namespace QKD.BB84.Engine

/-! ## The Bell de Finetti purification reference object -/

/-- **The Bell de Finetti purification reference** `τ_Bell` on the paired
`(4^n)·(4^n)` register: the explicit square-root/vectorization purification
`(√τ_Bell ⊗ 𝟙)|Ω⟩⟨Ω|(√τ_Bell ⊗ 𝟙)†` of the Bell de Finetti A-marginal
`bb84BellDeFinettiDensity n`.  Explicit; no `Classical.choose`.

Reference: Nahar et al. 2024 (arXiv:2403.11851) Lemma 2 (`x = 4`, joint Bell `ℤ₂×ℤ₂` symmetry); CKMR
Lemma II.5 (the square-root purification, `InfoTheory.DeFinetti.purificationDensityOp`). -/
noncomputable def bb84BellCKRDeFinettiPurification (n : ℕ) [NeZero n] :
    DensityOp ((4 ^ n) * (4 ^ n)) :=
  haveI : NeZero ((4 : ℕ) ^ n) := ⟨pow_ne_zero n (by norm_num)⟩
  InfoTheory.DeFinetti.purificationDensityOp (Quantum.Symmetry.bb84BellDeFinettiDensity n)

/-- **A pure state whose `4^n` marginal is the Bell de Finetti state.**  The Bell analogue
of `Quantum.Channels.IsCKRDeFinettiPurification`, with `ckrDeFinettiState` replaced by the
Bell de Finetti A-marginal `bb84BellDeFinettiDensity`. -/
structure IsBellCKRDeFinettiPurification {n dimR : ℕ} [NeZero n]
    (τ : DensityOp ((4 ^ n) * dimR)) : Prop where
  isPure : τ.IsPure
  marginal : τ.partialTraceB = Quantum.Symmetry.bb84BellDeFinettiDensity n

/-- The explicit `bb84BellCKRDeFinettiPurification` is a Bell CKR de Finetti purification:
it is pure and its `4^n` marginal equals `bb84BellDeFinettiDensity n`. -/
theorem bb84BellCKRDeFinettiPurification_isPurification (n : ℕ) [NeZero n] :
    IsBellCKRDeFinettiPurification (bb84BellCKRDeFinettiPurification n) := by
  haveI : NeZero ((4 : ℕ) ^ n) := ⟨pow_ne_zero n (by norm_num)⟩
  refine ⟨?_, ?_⟩
  · exact InfoTheory.DeFinetti.purificationDensityOp_isPure _
  · exact InfoTheory.DeFinetti.purificationDensityOp_partialTraceB _

end QKD.BB84.Engine

end -- noncomputable section
