import Mathlib.Data.Nat.Choose.Basic

/-!
# Four-letter symmetric dimension

`bellSymmetricDim n = Nat.choose (n + 3) 3` counts degree-`n` monomials in four variables.
It is positive for every `n` and supplies the Bell-symmetric postselection prefactor.
-/

namespace Math.Combinatorics

/-- **The Bell de Finetti dimension** `C(n+3,3)`: the dimension of the Bell-diagonal
symmetric subspace generated by the four commuting Bell projectors (the `d_Bell = 4`
symmetric-subspace count `C(n + d_Bell - 1, d_Bell - 1)`).  It is the rank of the Bell de
Finetti reference `Quantum.Symmetry.bellDeFinettiDensity n` (which normalizes by exactly
`C(n+3,3)`),
and it replaces the full CKR dimension `ckrSymmetricDim n = C(n+15,15)` in the Bell-symmetric
postselection reduction. -/
noncomputable def bellSymmetricDim (n : ℕ) : ℕ :=
  Nat.choose (n + 3) 3

/-- `bellSymmetricDim n ≥ 1` for all `n`. -/
lemma bellSymmetricDim_pos (n : ℕ) : 0 < bellSymmetricDim n :=
  Nat.choose_pos (by omega)

end Math.Combinatorics
