import Mathlib.Data.Nat.Choose.Basic

/-!
# The Bell de Finetti dimension `C(n+3,3)`

`bb84PolyDimTight` is the dimension of the Bell-diagonal symmetric subspace generated by the
four commuting Bell projectors — the `d_Bell = 4` symmetric-subspace count
`C(n + d_Bell - 1, d_Bell - 1)` — which replaces the full CKR dimension
`bb84PolyDim n = C(n+15,15)` in the Bell-tightened postselection reduction. Pure scalar
definition with its elementary lemma; no quantum content.

Reference: Nahar, Tupkary, Zhao, Lütkenhaus, Tan 2024 (`arXiv:2403.11851`),
`main.tex:354` `\label{lem:groupPurification}` — the general-compact-`G`
statement, at `x = ∑ᵢ mᵢ² = 4` for the joint Bell `ℤ₂×ℤ₂` symmetry (four one-dimensional irreps on
`ℂ⁴`), giving the exponent `x − 1 = 3`.  **Not** `main.tex:362` `\label{cor:symmetryDeFinetti}`,
which is stated only for a product group `G = G_A × G_B` and does not cover the bilateral group.
-/

namespace QKD.BB84.Engine

/-- **The Bell de Finetti dimension** `C(n+3,3)`: the dimension of the Bell-diagonal
symmetric subspace generated by the four commuting Bell projectors (the `d_Bell = 4`
symmetric-subspace count `C(n + d_Bell - 1, d_Bell - 1)`).  It is the rank of the Bell de
Finetti reference `bb84BellDeFinettiDensity n` (which normalizes by exactly `C(n+3,3)`),
and it replaces the full CKR dimension `bb84PolyDim n = C(n+15,15)` in the Bell-tightened
postselection reduction. -/
noncomputable def bb84PolyDimTight (n : ℕ) : ℕ :=
  Nat.choose (n + 3) 3

/-- `bb84PolyDimTight n ≥ 1` for all `n`. -/
lemma bb84PolyDimTight_pos (n : ℕ) : 0 < bb84PolyDimTight n :=
  Nat.choose_pos (by omega)

end QKD.BB84.Engine
